name: Level 2 - Koopa's Fortress

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

        # TODO - Configureer JDK 21 - hint: wellicht ook iets met actions?

        # TODO - Setup Gradle

        # TODO - Run een gradle test command

        # TODO - Upload een test rapport met het resultaat van de gedraaide testen